import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Router, { withRouter } from 'next/router'
import React from "react";
export default function Home() {
  React.useEffect(() => {
    Router.push("/login");
  });


 
  return (
    <div className={styles.container}>
        
        
      
      <Head>
        <title>Тавтай морилно уу</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


    </div>
  )
}
